### ISSUE TITLE
Commit are too much verbose since the latest update

### ISSUE THREAD

**Issue by DylanDelobel** [Blarc/ai-commits-intellij-plugin#12]
Hey 👋  
I think commit message should stay concice and short cf https://cbea.ms/git-commit/

Change in my code
```diff
const joinClanButton = new ActionRowBuilder<ButtonBuilder>()
    .addComponents(
        new ButtonBuilder()
+            .setLabel(`Rejoindre ${clan.name}`)
-            .setLabel(`Rejoindre clan name`)
            .setStyle(ButtonStyle.Link),
     );
```
Here mutliple result I feel to much

> The only change in this code is the label of the joinClanButton. Instead of a fixed label "Rejoindre le Clan", it now uses a dynamic label that includes the name of the clan: `Rejoindre ${clan.name}`. This makes the button more informative for the user and helps to differentiate between multiple clans. No other changes were made in this file.

344 CHARACTERS

> The change in this diff is a simple update to a label in a Discord embed message. The label for a button that allows users to join a Clash of Clans clan is updated to include the name of the clan. This change makes it clearer to users which clan they are joining when they click the button.

290 CHARACTERS

> The change in this commit modifies the label of the "Join Clan" button in the embed message sent by the BrulerieBot. Instead of just displaying "Rejoindre le Clan," it now displays "Rejoindre" followed by the name of the clan. This change makes it clearer to the user which clan they are joining when they click the button. No other changes were made in this commit.

366 CHARACTERS

All of theses commits message would not fit a git history, github commit page, or anything that list commits
Would you like to make some changes on this? 🙏 
Is there a way to downgrade to 0.4 on the build 231 ? 🤔

**Comment by Blarc** [comment]
I completely agree with you about how the commits should look like. Really interesting that you noticed this change after the latest update, since I haven't changed any of the logic around commit message creation (or at least I think so). The only explanation would be, that the OpenAI model has changed somehow.

I will add an option for setting your own prompt for OpenAI so you can experiment and change it to your needs.

If you would like to try to downgrade to previous version of the plugin, you can do so by following the steps in the readme: https://github.com/Blarc/ai-commits-intellij-plugin#installation-from-zip.

Thanks.

**Comment by DylanDelobel** [comment]
@Blarc Are you sure that OpenAI changed something?

I'm still using aicommit where I found your project here https://github.com/Nutlope/aicommits/issues/73

With their latest version that still look fine 
![image](https://user-images.githubusercontent.com/5182186/230103738-887c4dcd-e922-47cb-9f2d-e446b7343a16.png)

If you have a new build to try I have a ton's of untracked files I could add to my repo and give you feedback 👍

**Comment by DylanDelobel** [comment]
@Blarc I tried your exact promt with one line change and the result is what I expect,
I may think `getPrompt` is not called correctly?
![image](https://user-images.githubusercontent.com/5182186/230105753-5f6728a3-c7d7-46b9-8c2a-fdb459377f53.png)

**Comment by Blarc** [comment]
You used `git diff` to compute the diff based on which the commit message was generated, correct? Because plugin uses Intellij's implementation for computing the diff. Maybe that's the problem?

**Comment by DylanDelobel** [comment]
Yes I used `git diff`

Can you log what Intellij's implementation for computing the diff gave you comparing to `git diff` ?
You added this to v0.5 ?

**Comment by DylanDelobel** [comment]
@Blarc Can you log the full promt ? with your prefix in `getPrompt`

Note that the latest builds of Jetbrains IDE have changes in Git 
https://www.jetbrains.com/phpstorm/whatsnew/#version-2023-1-vcs--git--github

Could the two first lines breaks the formattings somehow to a regular `git diff` from the CLI ?
```diff
- Index: src/games/mine/Mine.py
- ===================================================================
```

**Comment by Blarc** [comment]
Ok, I found the bug. It's embarrassing: https://github.com/Blarc/ai-commits-intellij-plugin/blame/d200ef840b685cff10f9ccbd62d249a052d61d46/src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitAction.kt#L58

It should be `prompt` instead of `diff` here.

Will release bugfix asap. Sorry for the inconvenience and thanks for the help.

**Comment by Blarc** [comment]
Fixed in: https://github.com/Blarc/ai-commits-intellij-plugin/commit/a759819a19afbcca6ec6f368caa52d0e15caebb8.
