### ISSUE TITLE
[Feature Request]Support for Ollama

### ISSUE THREAD

**Issue by danny-su** [Blarc/ai-commits-intellij-plugin#132]
Support for Ollama

**Comment by flrs** [comment]
This is, in principle, already possible, since Ollama is [compatible](https://ollama.com/blog/openai-compatibility) with the OpenAI API. The limiting factor is that the ai-commits extension insists on a model being named "gpt-4" or "gpt-3.5-turbo". To use a custom model in Ollama, you need to create a modelfile that disguises the model of your choice as a model with either of these names.

Here is **a workaround** to use Ollama in IntelliJ today:

1. Create a modelfile from your favorite model, e.g. for gemma:

```
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
FROM gemma:7b-instruct

TEMPLATE """<start_of_turn>user
{{ if .System }}{{ .System }} {{ end }}{{ .Prompt }}<end_of_turn>
<start_of_turn>model
{{ .Response }}<end_of_turn>
"""
PARAMETER repeat_penalty 1
PARAMETER stop "<start_of_turn>"
PARAMETER stop "<end_of_turn>"
```

2. Create this model via ollama:
```bash
ollama create gpt-4 -f ./modelfile
```

3. In the AI Commits tool settings in IntelliJ, add the following settings:

- OpenAI host: `http://127.0.0.1:11434/v1/`
- OpenAI token: `ollama`
- OpenAI model: `gpt-4`

**Comment by Blarc** [comment]
Hey @flrs, thanks a lot for this workaround :pray: . I am working on supporting multiple LLM providers in branch `generic-ai-providers`. You can expect this to be added soon :smiley: .

**Comment by danny-su** [comment]
Thank you both.

**Comment by Blarc** [comment]
Hey @chachako, the models are currently fetched from OpenAI API. If you have the subscription that enables you to use GPT 4-32k or some other models, you should be able to use them already.

The new implementation that I am working on is a more general architecture that allows adding new LLM providers easier. Which models will be available will depend on the LLM provider and the models it supports.

**Comment by chachako** [comment]
> Hey @chachako, the models are currently fetched from OpenAI API. If you have the subscription that enables you to use GPT 4-32k or some other models, you should be able to use them already.

@Blarc Ah yes! In most cases, that's true, but I forgot to mention one thing: I am using a third-party OpenAI API host, which does not provide a list of models. It also has some specific models for me to use. Therefore, in these special scenarios, having a custom option might be better.

If you don't mind, I can pull a request for this. In fact, I forked and try this shortly before several hours ago :)

**Comment by Blarc** [comment]
@chachako Hmm... maybe I can make the dropdown similar to the dropdown for `OpenAI host`, so custom model names can be added. I'll look into it.

**Comment by Blarc** [comment]
Support for Ollama was added in version [2.0.0](https://github.com/Blarc/ai-commits-intellij-plugin/releases/tag/v2.0.0).
