### ISSUE TITLE
Locale Parameter Not Respecting Language Choice for Commit Messages

### ISSUE THREAD

**Issue by Johnnni** [Blarc/ai-commits-intellij-plugin#181]
Hello,

I have noticed an issue with the "ai commit" regarding the generation of commit messages. It appears that the commit messages are not being generated in the language specified by the "locale" parameter. Regardless of the selected locale, the commit messages are consistently produced in the default language.

Steps to Reproduce:

1. Set up the "ai commit".

2. Configure the locale parameter to a any language

3. Generate a commit message using the tool.

4. Observe the generated commit message.

Expected Result:

- The commit message should be generated in the language specified by the locale parameter (e.g., French, or portuguese).

Actual Result:

- The commit message is generated in english instead of the chosen locale.

**Comment by Blarc** [comment]
Hey @Johnnni,

the locale parameter is just a variable that can be set in the prompt with `{locale}`. So whether the LLM creates the commit message in a given locale depends entirely on the prompt. Since LLMs don't work purely deterministically it can also happen that the LLM ignores the locale. You can set how deterministic the LLM should be with the temperature property.
