### ISSUE TITLE
Edit Prompt window too wide

### ISSUE THREAD

**Issue by vadviktor** [Blarc/ai-commits-intellij-plugin#287]
Hey @Blarc ,

I have a UX issue with the Edit Prompt window.

When the Content has very long lines without line breaks, it stretches the window off from the screen, and I am not even able to resize it.
The other issue on top of it is that when such long lines are in the text area, the window adjusts itself slowly and with massive flickering. 😵 

My guess is the culprit is that the text area is not allowed to have horizontal scrollbars.

The workaround on my end is to first edit the texts copied from other sources.

Would it be possible to look into this, please? 🙏

**Comment by Blarc** [comment]
Hey @vadviktor ,
I'll look into this.

**Comment by Blarc** [comment]
Hey @vadviktor,

I can't repeat this issue. I tried making a really long line without line breaks and wrapped fine:
![image](https://github.com/user-attachments/assets/7b3ddcc2-46d2-4968-a81b-57a48c8b37f2)

Could you maybe provide a recording of this issue happening?

Thanks :pray: .

**Comment by vadviktor** [comment]
Hey @Blarc ,

sure! I've recorded and uploaded the recording here https://youtu.be/W99ktvDaIgc

I am using Windows 11, and my IDE is now Rider. As you can see, I cannot make the modal smaller depending on the amount of text in it.

_Another issue with the modal: the diff generation makes it very laggy (and sometimes impossible) to type into it. This is just something I mention because it would need a separate ticket 😅_

**Comment by Blarc** [comment]
Ah... yeah, once you resize the dialog, the size is saved but you can't resize it back. Saving of dialog size was added in https://github.com/Blarc/ai-commits-intellij-plugin/commit/084c7a4b33067a99bc5225904f2f44d52fad021a which made this possible. 

I'll look into it...

**Comment by Blarc** [comment]
So this is a bit tricky and I am not sure how to fix this. The code for this dialog can be found here: https://github.com/Blarc/ai-commits-intellij-plugin/blob/63308e4ab7fc3f9802541413756548d8b885c7bf/src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/prompts/PromptTable.kt#L127-L158.

I've had a lot of problems implementing this in the first place, because the text wouldn't wrap properly etc. Since this is causing problems, I'm thinking about reverting the change that added the saving of dialog size (https://github.com/Blarc/ai-commits-intellij-plugin/commit/084c7a4b33067a99bc5225904f2f44d52fad021a). I feel that is not as important, since you can always resize. The problem currently is more annoying, since you can't resize back.

What do you think @vadviktor ? 

(Sorry if I'm rambling a bit...)

**Comment by vadviktor** [comment]
Thanks for looking into this @Blarc, really appreciate it! 🙏 

This is definitely not going to block anyone from using the plugin. It is only UX.
As I stated earlier, when I figured this out and broke the text into narrower pieces before pasting, it didn't block me from using the plugin.

We can close this ticket now and if anyone comes up with a solution and a PR can reopen/ref it.
