### ISSUE TITLE
Hello, can you advise on this issue

### ISSUE THREAD

**Issue by dej00021** [Blarc/ai-commits-intellij-plugin#89]
![image_2023-09-12_092150780](https://github.com/Blarc/ai-commits-intellij-plugin/assets/48507414/3d18e6bc-6c24-490b-abc1-8cfb71595c77)

**Comment by Blarc** [comment]
Are you using AI Commits and forked project Commit GPT plugins together?

From the error message I think the forked project didn't change the key for saving plugin settings and that's why you get `Key com.github.blarc.ai.commits.intellij.plugin.settings.AppSettings duplicated`.

I would advise you to uninstall both plugins and install only one of them.

Hope this helps. :pray:
